#!/bin/bash

PATH=/usr/local/bin:$PATH
script_dir="$(cd "$(dirname "${BASH_SOURCE:-$0}")"; pwd)"

cd ${script_dir}
export NODE_ENV=production
export NODE_CONFIG_DIR=${script_dir}/config

forever start ${script_dir}/server.js
